services:
  metastore:
    image: postgres:11
    hostname: metastore
    environment:
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - metastore:/var/lib/postgresql/data
      - ./metastore/ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  master:
    image: hadoop-spark-master
    hostname: master
    depends_on:
      - metastore
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "metastore:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker1:
    image: hadoop-spark-worker
    hostname: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker2:
    image: hadoop-spark-worker
    hostname: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "history:172.28.1.5"

  history:
    image: hadoop-spark-history
    hostname: history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: history
    ports:
      - "18080:18080"
      - "19888:19888"
    volumes:
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.5
    extra_hosts:
      - "metastore:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  metastore:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16