services:
  postgres:
    image: postgres:11
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: jupyter
      POSTGRES_PASSWORD: jupyter
    ports:
      - "5432:5432"
    volumes:
      - hive-db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      sparknet:
        ipv4_address: 172.28.1.1
    extra_hosts:
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  master:
    image: hadoop-spark-master
    hostname: master
    container_name: master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.2
      SPARK_LOCAL_HOSTNAME: master
    ports:
      - "4040:4040"
      - "8020:8020"
      - "8080:8080"
      - "8088:8088"
      - "9870:9870"
      - "8032:8032"   # YARN ResourceManager
      - "8030:8030"   # YARN ResourceManager Scheduler
    volumes:
      - namenode:/opt/hadoop/dfs/name
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: unless-stopped
    networks:
      sparknet:
        ipv4_address: 172.28.1.2
    extra_hosts:
      - "postgres:172.28.1.1"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker1:
    image: hadoop-spark-worker
    hostname: worker1
    container_name: worker1
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.3
      SPARK_LOCAL_HOSTNAME: worker1
    ports:
      - "8042:8042"
      - "8081:8081"
      - "9864:9864"
    volumes:
      - datanode1:/opt/hadoop/dfs/data
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.3
    extra_hosts:
      - "postgres:172.28.1.1"
      - "master:172.28.1.2"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  worker2:
    image: hadoop-spark-worker
    hostname: worker2
    container_name: worker2
    depends_on:
      - master
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.4
      SPARK_LOCAL_HOSTNAME: worker2
    ports:
      - "8043:8042"
      - "8082:8081"
      - "9865:9864"
    volumes:
      - datanode2:/opt/hadoop/dfs/data
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.4
    extra_hosts:
      - "postgres:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "history:172.28.1.5"

  history:
    image: hadoop-spark-history
    hostname: history
    container_name: history
    depends_on:
      - master
      - worker1
      - worker2
    environment:
      SPARK_MASTER_HOST: 172.28.1.2
      SPARK_LOCAL_IP: 172.28.1.5
      SPARK_LOCAL_HOSTNAME: history
    ports:
      - "18080:18080"
      - "19888:19888"
    volumes:
      - ./base/conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./base/conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./base/conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./base/conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./base/conf/workers:/opt/hadoop/etc/hadoop/workers
      - ./base/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./base/conf/log4j.properties:/opt/spark/conf/log4j.properties
      - ./base/conf/workers:/opt/spark/conf/workers
    restart: always
    networks:
      sparknet:
        ipv4_address: 172.28.1.5
    extra_hosts:
      - "postgres:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"

  # Nowe usługi Hive
  metastore:
    image: apache/hive:3.1.3
    hostname: metastore
    container_name: metastore
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >-
        -Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=jupyter
        -Djavax.jdo.option.ConnectionPassword=jupyter
      HIVE_CUSTOM_CONF_DIR: /hive_custom_conf
    ports:
      - "9083:9083"
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./base/conf:/hive_custom_conf
      - ./base/lib/postgresql-42.3.2.jar:/opt/hive/lib/postgresql-42.3.2.jar
    networks:
      sparknet:
        ipv4_address: 172.28.1.6
    extra_hosts:
      - "postgres:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

  hiveserver2:
    image: apache/hive:3.1.3
    hostname: hiveserver2
    depends_on:
      - metastore
    restart: unless-stopped
    container_name: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: "-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083"
      IS_RESUME: "true"
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - warehouse:/opt/hive/data/warehouse
    networks:
      sparknet:
        ipv4_address: 172.28.1.7
    extra_hosts:
      - "postgres:172.28.1.1"
      - "master:172.28.1.2"
      - "worker1:172.28.1.3"
      - "worker2:172.28.1.4"
      - "history:172.28.1.5"

volumes:
  namenode:
  namesecondary:
  datanode1:
  datanode2:
  hive-db:
  warehouse:

networks:
  sparknet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16